# Copyright (C) 2017-2018 Project-ODE
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


# ODE FeatureService example config
# Author: Joseph Allemandou


feature_service_project: &feature_service_project
  x-modules:
    - path: projects/feature_service_default.yaml
      options: &default_options
        elasticSearch:
          scheme: http
          host: localhost
          port: 9200
          maximumSize: 1000
          index: ode_data
        authentication:
          # You can generate a new secret on a linux system for example with the following command:
          # cat /dev/urandom | tr -dc A-Za-z0-9 | head -c 128 ; echo ''
          secret: GENERATE NEW SECRET PLEASE
          token_lifetime: 1h
        annotation-task:
          play_url: "http://localhost:7231/data.ode.org/v1/test/sound/$filename/play"
          spectro_url: "http://localhost:7231/data.ode.org/v1/spectro/"

# Swagger spec root.
spec: &spec_root
  title: "The ODE FeatureService root"
  x-sub-request-filters:
    - type: default
      name: http
      options:
        allow:
          - pattern: /^http:\/\/localhost:9200\/.*/
            forward_headers: true
  paths:
    /{domain:data.ode.org}: *feature_service_project

# The main service setup. Each worker can offer one or more services.
services:
  - name: feature-service
    module: hyperswitch
    conf:
      port: 7231
      spec: *spec_root
      salt: secret
      default_page_size: 125

logging:
  name: feature-service
  level: info
  #streams:
  #- type: gelf
  #  host: <%= @logstash_host %>
  #  port: <%= @logstash_port %>

metrics:
  #type: txstatsd
  #host: localhost
  #port: 8125
  #batch: true
