# Copyright (C) 2017-2018 Project-ODE
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


# Test configuration for ODE-FeatureService
# Author: Joseph Allemandou


# A synthetic domain to test ODE-FeatureService
default_project: &default_project
  x-modules:
    - path: test/fs_test_module.yaml
    - path: projects/feature_service_default.yaml
      options: &default_options
        elasticSearch:
          path: /data.ode.org/sys/fake-es/es
          maximumSize: 10000
          index: ode_data
        authentication:
          htpasswd: test/htpasswd
          secret: fake-test-secret
          token_lifetime: 1h


spec_root: &spec_root
  title: "The ODE FeatureService root"
  paths:
    /{domain:data.ode.org}: *default_project

# Finally, a standard service-runner config.
info:
  name: feature-service

services:
  - name: feature-service
    module: hyperswitch
    conf:
      port: 7231
      spec: *spec_root
      salt: secret
      default_page_size: 1
      user_agent: feature-service-testsuite

logging:
  name: feature-service
  level: info

metrics:
